### ISSUE TITLE
DFS: empty range for randrange()

### ISSUE THREAD

**Issue by yoavgil** [cjdhein/perseus#17]
This error was found on the master branch. It happens with DFS, not with BFS.

I searched for the following:
URL: google.com
Search method: DFS
Numeric limit: 1

  File "core.py", line 41, in <module>
    testTree.beginCrawl()
  File "/home/ygil/perseus/server/pagetree.py", line 182, in beginCrawl
    i = random.randrange(len(aNode.urlList))
  File "/usr/lib/python2.7/random.py", line 195, in randrange
    raise ValueError, "empty range for randrange()"

**Comment by cjdhein** [comment]
Resolved. I believe this was due to an issue with the URL being passed. I implemented a check that will prepend http if no scheme is included in the URL.
