### ISSUE TITLE
Invalid URL Host "http:///"

### ISSUE THREAD

**Issue by yoavgil** [cjdhein/perseus#35]
This error occurs on "google.com/about".
pipenv run python3 core.py crawler_log_8xU5t2rHX.xml google.com/about 1 1

Each time it runs, it may have an error such as the following (depending on the child page it tries to visit).

Invalid URL 'http:///about/our-commitments': No host supplied
Invalid URL 'http:///about/our-story': No host supplied

The page source for "https://www.google.com/about/" shows the following:
<a href="./our-commitments/
and
<a href="./our-story"

**Comment by cjdhein** [comment]
Resolved. Parser now handles ./
