### ISSUE TITLE
Page Limit for DFS / BFS

### ISSUE THREAD

**Issue by cjdhein** [cjdhein/perseus#9]
Decide maximum page limit for DFS and BFS. Implement error handling if the user inputs a page limit that is too high. (Error handling will be implemented on front end, server, and crawler.)

**Comment by cjdhein** [comment]
I will run some tests with different limits for both and see what seems reasonable

**Comment by yoavgil** [comment]
On the server-3.0 branch I am working on (not yet merged with master), I used the following values:
BFS page limit: 3
DFS page limit: 100

However, the 60 second timeout may occur even with these values.
